server:
  port: 8082
spring:
  application:
    name: userservice-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: 101.34.208.76:8848
        username: nacos
        password: phsz
        file-extension: yml
  config:
    import:
      - nacos:datasource?refresh=true
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: off
phsz:
  jwt:
    secret: Of0dtVLJL/iNa5tlASR8VXKRvAe7UEqETaC4s0EtePo=
    expiration: 86400000
logging:
    level:
        root: info
