server:
  port: 9005
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: hospitalizationservice-provider
  datasource:
    url: jdbc:postgresql://101.34.208.76:5432/phsz
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: off
phsz:
  jwt:
    secret: Of0dtVLJL/iNa5tlASR8VXKRvAe7UEqETaC4s0EtePo=
    expiration: 3600000