server:
  port: 10010
phsz:
  jwt:
    secret: Of0dtVLJL/iNa5tlASR8VXKRvAe7UEqETaC4s0EtePo=
    expiration: 86400000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    loadbalancer:
      ribbon:
        enable: false
    gateway:
      routes:
        - id: caseservice-provider
          uri:
            lb://caseservice-provider
          predicates:
            - Path=/api/cases/**,/api/diseases/**,/api/assays/**,/api/medicines/**,/api/vaccines/**,/api/charges/**
        - id: clerkservice-provider
          uri:
            lb://clerkservice-provider
          predicates:
            - Path=/api/clerks/**
        - id: documentservice-provider
          uri:
            lb://documentservice-provider
          predicates:
            - Path=/api/documents/**
        - id: hospitalizationservice-provider
          uri:
            lb://hospitalizationservice-provider
          predicates:
            - Path=/api/hospitalizations/**
        - id: officeservice-provider
          uri:
            lb://officeservice-provider
          predicates:
            - Path=/api/offices/**
        - id: roleplayservice-provider
          uri:
            lb://roleplayservice-provider
          predicates:
            - Path=/api/plays/**
        - id: testservice-provider
          uri:
            lb://testservice-provider
          predicates:
            - Path=/api/test/**
        - id: userservice-provider
          uri:
            lb://userservice-provider
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: fileuploadservice-provider
          uri:
              lb://fileuploadservice-provider
          predicates:
              - Path=/oss/**
        - id: agi-provider
          uri:
            lb://agi-provider
          predicates:
            - Path=/api/chats/**, /api/docs/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE