server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: 101.34.208.76:8848
        username: nacos
        password: phsz
        file-extension: yml
  config:
    import:
      - nacos:datasource?refresh=true
  application:
    name: testservice-provider
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: off

logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug